import { spawnSync } from 'node:child_process';
import { copyFile, mkdir, mkdtemp, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { afterEach, describe, expect, it } from 'vitest';

const temporaryRoots: string[] = [];

const packageFixture = {
  name: 'chronoage',
  version: '2.0.12',
  dependencies: {
    react: '19.2.8',
  },
  devDependencies: {
    vite: '8.2.1',
  },
};

async function createFixture() {
  const root = await mkdtemp(join(tmpdir(), 'chronoage-lockfiles-'));
  temporaryRoots.push(root);
  await mkdir(join(root, 'scripts'), { recursive: true });
  await mkdir(join(root, 'src-tauri'), { recursive: true });
  await copyFile(
    new URL('../scripts/check-lockfiles.mjs', import.meta.url),
    join(root, 'scripts', 'check-lockfiles.mjs'),
  );
  await writeFile(join(root, 'package.json'), JSON.stringify(packageFixture, null, 2));
  await writeFile(
    join(root, 'src-tauri', 'Cargo.toml'),
    '[package]\nname = "chronoage"\nversion = "2.0.12"\n',
  );
  return root;
}

function runPreflight(root: string, ...args: string[]) {
  return spawnSync(process.execPath, [join(root, 'scripts', 'check-lockfiles.mjs'), ...args], {
    encoding: 'utf8',
  });
}

async function writeValidNpmLockfile(root: string) {
  await writeFile(
    join(root, 'package-lock.json'),
    JSON.stringify(
      {
        name: packageFixture.name,
        version: packageFixture.version,
        lockfileVersion: 3,
        requires: true,
        packages: {
          '': {
            name: packageFixture.name,
            version: packageFixture.version,
            dependencies: packageFixture.dependencies,
            devDependencies: packageFixture.devDependencies,
          },
        },
      },
      null,
      2,
    ),
  );
}

async function writeValidCargoLockfile(root: string) {
  await writeFile(
    join(root, 'src-tauri', 'Cargo.lock'),
    '# This file is automatically @generated by Cargo.\n# It is not intended for manual editing.\nversion = 4\n\n[[package]]\nname = "chronoage"\nversion = "2.0.12"\n',
  );
}

afterEach(async () => {
  await Promise.all(temporaryRoots.splice(0).map((root) => rm(root, { recursive: true, force: true })));
});

describe('release lockfile preflight', () => {
  it('accepts a matching npm lockfile', async () => {
    const root = await createFixture();
    await writeValidNpmLockfile(root);

    const result = runPreflight(root, '--npm');

    expect(result.status).toBe(0);
    expect(result.stdout).toContain('Release lockfile preflight passed for: npm.');
  });

  it('rejects a missing npm lockfile', async () => {
    const root = await createFixture();

    const result = runPreflight(root, '--npm');

    expect(result.status).toBe(1);
    expect(result.stderr).toContain('package-lock.json is missing');
  });

  it('rejects npm root dependency drift', async () => {
    const root = await createFixture();
    await writeValidNpmLockfile(root);
    const mismatched = {
      ...packageFixture,
      dependencies: { react: '19.2.7' },
    };
    await writeFile(join(root, 'package.json'), JSON.stringify(mismatched, null, 2));

    const result = runPreflight(root, '--npm');

    expect(result.status).toBe(1);
    expect(result.stderr).toContain('dependencies do not exactly match package.json');
  });

  it('accepts a generated Cargo lockfile containing the root package', async () => {
    const root = await createFixture();
    await writeValidCargoLockfile(root);

    const result = runPreflight(root, '--cargo');

    expect(result.status).toBe(0);
    expect(result.stdout).toContain('Release lockfile preflight passed for: cargo.');
  });

  it('rejects a missing Cargo lockfile', async () => {
    const root = await createFixture();

    const result = runPreflight(root, '--cargo');

    expect(result.status).toBe(1);
    expect(result.stderr).toContain('src-tauri/Cargo.lock is missing');
  });

  it('checks both lockfiles by default', async () => {
    const root = await createFixture();
    await writeValidNpmLockfile(root);
    await writeValidCargoLockfile(root);

    const result = runPreflight(root);

    expect(result.status).toBe(0);
    expect(result.stdout).toContain('Release lockfile preflight passed for: npm, cargo.');
  });

  it('rejects unknown targets', async () => {
    const root = await createFixture();

    const result = runPreflight(root, '--unknown');

    expect(result.status).toBe(2);
    expect(result.stderr).toContain('Unknown lockfile target --unknown');
  });

  it('does not let --all mask an unknown target', async () => {
    const root = await createFixture();

    const result = runPreflight(root, '--all', '--unknown');

    expect(result.status).toBe(2);
    expect(result.stderr).toContain('Unknown lockfile target --unknown');
  });
});
